# frozen_string_literal: true

require "test_helper"

class UnseekableIoStreamingTest < Test::Unit::TestCase
  # A minimal write-only sink that does not support pos, tell, seek, or rewind.
  class MinimalUnseekableSink
    attr_reader :buffer

    def initialize
      @buffer = +""
      @closed = false
    end

    def write(data)
      raise IOError, "closed stream" if @closed

      @buffer << data.b
      data.bytesize
    end

    def close
      @closed = true
    end

    def closed?
      @closed
    end
  end

  def test_generate_with_minimal_unseekable_sink
    sink = MinimalUnseekableSink.new

    Xlsxrb.write(sink) do |wb|
      wb.sheet("Sales") do |sheet|
        sheet.row(%w[Product Qty Price Total])
        sheet.row(["Apple", 10, 1.5, Xlsxrb.formula("B2*C2", cached_value: 15.0)])
        sheet.row(["Banana", 20, 0.75, Xlsxrb.formula("B3*C3", cached_value: 15.0)])
      end

      wb.sheet("Summary") do |sheet|
        sheet.row(%w[Item Value])
        sheet.row(["Total Qty", 30])
      end
    end

    sink.close
    assert_true sink.closed?
    assert_operator sink.buffer.bytesize, :>, 0

    # Parse back the generated bytes from memory to verify validity
    workbook = Xlsxrb.read(StringIO.new(sink.buffer)).load
    assert_equal 2, workbook.sheets.size

    sales = workbook.sheets[0]
    assert_equal "Sales", sales.name
    assert_equal 3, sales.rows.size
    assert_equal %w[Product Qty Price Total], sales.rows[0].cells.map(&:value)
    assert_equal ["Apple", 10, 1.5, 15.0], sales.rows[1].cells.map(&:value)

    summary = workbook.sheets[1]
    assert_equal "Summary", summary.name
    assert_equal 2, summary.rows.size
    assert_equal ["Total Qty", 30], summary.rows[1].cells.map(&:value)
  end

  def test_generate_with_io_pipe_streaming
    reader, writer = IO.pipe
    reader.binmode
    writer.binmode

    collected_data = +""
    read_thread = Thread.new do
      while (chunk = reader.read(4096))
        collected_data << chunk
      end
    ensure
      reader.close
    end

    write_thread = Thread.new do
      Xlsxrb.write(writer) do |wb|
        wb.sheet("LargeStream") do |sheet|
          sheet.row(%w[ID Name Date])
          500.times do |i|
            sheet.row([i + 1, "User #{i + 1}", Date.new(2026, 1, 1)])
          end
        end
      end
    ensure
      writer.close
    end

    write_thread.join
    read_thread.join

    assert_operator collected_data.bytesize, :>, 0

    # Verify that the generated stream is a completely valid XLSX workbook
    workbook = Xlsxrb.read(StringIO.new(collected_data)).load
    assert_equal 1, workbook.sheets.size

    sheet = workbook.sheets[0]
    assert_equal "LargeStream", sheet.name
    assert_equal 501, sheet.rows.size
    assert_equal %w[ID Name Date], sheet.rows[0].cells.map(&:value)
    assert_equal 1, sheet.rows[1].cells[0].value
    assert_equal "User 1", sheet.rows[1].cells[1].value
    assert_equal Date.new(2026, 1, 1), sheet.rows[1].cells[2].to_date
    assert_equal 500, sheet.rows[500].cells[0].value
    assert_equal "User 500", sheet.rows[500].cells[1].value
    assert_equal Date.new(2026, 1, 1), sheet.rows[500].cells[2].to_date
  end

  def test_generate_with_styled_cells_on_unseekable_sink
    sink = MinimalUnseekableSink.new

    Xlsxrb.write(sink) do |wb|
      wb.style("header", font: { bold: true }, fill: { color: "CCE5FF" })
      wb.style("currency", number_format: "$#,##0.00")

      wb.sheet("Invoices") do |sheet|
        sheet.row(["Invoice #", "Amount"], styles: "header")
        sheet.row(["INV-001", 1250.5], styles: [nil, "currency"])
        sheet.merge("A3:B3")
        sheet.row(["Merged Footer Note"])
      end
    end

    workbook = Xlsxrb.read(StringIO.new(sink.buffer)).load
    sheet = workbook.sheets[0]
    assert_equal "Invoices", sheet.name
    assert_equal 3, sheet.rows.size
    assert_equal ["Invoice #", "Amount"], sheet.rows[0].cells.map(&:value)
    assert_equal ["INV-001", 1250.5], sheet.rows[1].cells.map(&:value)
  end

  def test_foreach_streaming_read_from_unseekable_sink_output
    sink = MinimalUnseekableSink.new

    Xlsxrb.write(sink) do |wb|
      wb.sheet("StreamSheet") do |sheet|
        sheet.row(%w[A B])
        sheet.row([1, 2])
      end
    end

    read_rows = []
    Xlsxrb.read(StringIO.new(sink.buffer)) do |sheet|
      sheet.each_row do |row|
        read_rows << row.cells.map(&:value)
      end
    end

    assert_equal [%w[A B], [1, 2]], read_rows
  end

  def test_action_controller_live_buffer_mock
    # ActionController::Live::Buffer responds to write, but not pos, tell, or seek.
    mock_live_buffer = Class.new do
      attr_reader :chunks

      def initialize
        @chunks = []
      end

      def write(string)
        @chunks << string.dup
        string.bytesize
      end
    end.new

    Xlsxrb.write(mock_live_buffer) do |wb|
      wb.sheet("LiveSheet") do |sheet|
        sheet.row(%w[Timestamp Status])
        sheet.row(["2026-08-15T04:22:00Z", "OK"])
      end
    end

    combined = mock_live_buffer.chunks.join
    assert_operator combined.bytesize, :>, 0

    wb = Xlsxrb.read(StringIO.new(combined)).load
    assert_equal 1, wb.sheets.size
    assert_equal "LiveSheet", wb.sheets[0].name
    assert_equal %w[Timestamp Status], wb.sheets[0].rows[0].cells.map(&:value)
    assert_equal ["2026-08-15T04:22:00Z", "OK"], wb.sheets[0].rows[1].cells.map(&:value)
  end
end
