# frozen_string_literal: true

require "test_helper"
require "open3"
require "tempfile"

class ReaderInteroperabilityTest < Test::Unit::TestCase
  SCENARIO_DIR = File.expand_path("../fixtures/sdk_scenarios", __dir__)

  test "reader can parse inline string file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_inline_string_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple inline strings in the same row generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_same_row_multiple_inline_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse shared strings file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shared_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse numeric cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_numeric_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => 42, "B1" => 3.14 }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse boolean cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_boolean_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => true, "B1" => false }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse error cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_error_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_instance_of(Xlsxrb::CellError, cells["A1"])
    assert_equal("#DIV/0!", cells["A1"].code)
    assert_instance_of(Xlsxrb::CellError, cells["B1"])
    assert_equal("#VALUE!", cells["B1"].code)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse formula cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_formula_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_instance_of(Xlsxrb::Formula, cells["A3"])
    assert_equal("SUM(A1:A2)", cells["A3"].expression)
    assert_equal("30", cells["A3"].cached_value)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple sheets generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_multi_sheet_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[Sheet1 Data], reader.sheet_names)
    assert_equal({ "A1" => "main" }, reader.cells(sheet: "Sheet1"))
    assert_equal({ "A1" => "data" }, reader.cells(sheet: "Data"))
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse column widths generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_column_width_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cols = reader.columns
    assert_in_delta(20.0, cols["A"], 0.01)
    assert_in_delta(15.5, cols["C"], 0.01)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse row attributes generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_row_attributes_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    row_attrs = reader.row_attributes
    assert_in_delta(25.0, row_attrs[1][:height], 0.01)
    assert_equal(true, row_attrs[3][:hidden])
    assert_equal(0, row_attrs[5][:style])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader resolves cellXf xfId linkage generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cell_xf_xfid_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal("mm-dd-yy", reader.cell_formats["A1"])
    assert_equal("mm-dd-yy", reader.cell_styles["A1"][:num_fmt])
    assert_equal(Date.new(2024, 1, 1), reader.cells["A1"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse merge cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_merge_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[A1:B2 C3:D4], reader.merged_cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse hyperlinks generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_hyperlink_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => { url: "https://example.com" } }, reader.hyperlinks)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse hyperlinks with display tooltip and location from SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_hyperlink_deep_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    links = reader.hyperlinks
    expected = {
      "A1" => { url: "https://example.com", display: "Example Site", tooltip: "Click to visit" },
      "B1" => { url: "https://example.com/page", location: "Sheet2!A1" },
      "C1" => { location: "Sheet1!D1" }
    }
    assert_equal(expected, links)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse numFmt from styles generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_numfmt_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fmts = reader.cell_formats
    assert_equal("#,##0.00", fmts["A1"])
    assert_nil(fmts["B1"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader resolves built-in numFmt from styles generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_builtin_numfmt_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fmts = reader.cell_formats
    assert_equal("mm-dd-yy", fmts["A1"])
    assert_equal("@", fmts["B1"])
    styles = reader.cell_styles
    assert_equal("mm-dd-yy", styles["A1"][:num_fmt])
    assert_equal("@", styles["B1"][:num_fmt])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse date cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_date_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_equal(Date.new(2024, 1, 15), cells["A1"])
    assert_equal(42, cells["B1"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse auto filter generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_auto_filter_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal("A1:B10", reader.auto_filter)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse core properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_core_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.core_properties
    assert_equal("SDK Title", props[:title])
    assert_equal("SDK Creator", props[:creator])
    assert_not_nil(props[:created])
    assert_not_nil(props[:modified])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse app properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_app_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.app_properties
    assert_equal("SDK App", props[:application])
    assert_equal("2.0.0", props[:app_version])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse workbook properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_workbook_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    wp = reader.workbook_properties
    assert_equal(false, wp[:date1904])
    assert_equal(166_925, wp[:default_theme_version])

    wv = reader.workbook_views
    assert_equal(1, wv[:active_tab])
    assert_equal(0, wv[:first_sheet])

    cp = reader.calc_properties
    assert_equal(191_029, cp[:calc_id])
    assert_equal(true, cp[:full_calc_on_load])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet states generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_state_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    states = reader.sheet_states
    assert_equal(:visible, states["Sheet1"])
    assert_equal(:hidden, states["Hidden"])
    assert_equal(:very_hidden, states["VeryHidden"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse defined names generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_defined_names_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    dns = reader.defined_names
    assert_equal(3, dns.size)
    assert_equal("MyRange", dns[0][:name])
    assert_equal("Sheet1!$A$1:$B$10", dns[0][:value])
    assert_equal("LocalName", dns[1][:name])
    assert_equal(1, dns[1][:local_sheet_id])
    assert_equal("HiddenConst", dns[2][:name])
    assert_equal(true, dns[2][:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.sheet_properties
    assert_equal("FFFF0000", props[:tab_color])
    assert_equal(false, props[:summary_below])
    assert_equal(false, props[:summary_right])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet format properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_format_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fmt = reader.sheet_format
    assert_equal(20.0, fmt[:default_row_height])
    assert_equal(15.5, fmt[:default_col_width])
    assert_equal(12, fmt[:base_col_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse row and column attributes generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_row_col_attrs_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ra = reader.row_attributes
    assert_equal(1, ra[2][:outline_level])
    assert_equal(true, ra[3][:collapsed])

    ca = reader.column_attributes
    assert_equal(true, ca["B"][:hidden])
    assert_equal(2, ca["C"][:outline_level])
    assert_equal(true, ca["C"][:collapsed])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet view, pane, and selection generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_view_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    sv = reader.sheet_view
    assert_equal(false, sv[:show_grid_lines])
    assert_equal(120, sv[:zoom_scale])

    fp = reader.freeze_pane
    assert_equal(2, fp[:row])
    assert_equal(1, fp[:col])
    assert_equal(:frozen, fp[:state])

    sel = reader.selection
    assert_equal("D4", sel[:active_cell])
    assert_equal("D4", sel[:sqref])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse print/page elements generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_print_page_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    po = reader.print_options
    assert_equal(true, po[:grid_lines])
    assert_equal(true, po[:horizontal_centered])

    pm = reader.page_margins
    assert_in_delta(0.5, pm[:left], 0.001)
    assert_in_delta(1.0, pm[:top], 0.001)

    ps = reader.page_setup
    assert_equal("portrait", ps[:orientation])
    assert_equal(9, ps[:paper_size])
    assert_equal(80, ps[:scale])

    hf = reader.header_footer
    assert_equal("&LLeft Header", hf[:odd_header])
    assert_equal("&RRight Footer", hf[:odd_footer])

    assert_equal([5, 15], reader.row_breaks.map { |b| b[:id] })
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse filter columns and sort state generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_filter_sort_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fc = reader.filter_columns
    assert_equal(:filters, fc[0][:type])
    assert_equal(%w[Alice Bob], fc[0][:values])
    assert_equal(:custom, fc[1][:type])
    assert_equal("greaterThan", fc[1][:operator])

    ss = reader.sort_state
    assert_equal("A2:B10", ss[:ref])
    assert_equal(2, ss[:sort_conditions].size)
    assert_equal(true, ss[:sort_conditions][1][:descending])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse data validations generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_data_validation_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    dvs = reader.data_validations
    assert_equal(2, dvs.size)

    assert_equal("A2:A50", dvs[0][:sqref])
    assert_equal("whole", dvs[0][:type])
    assert_equal("greaterThanOrEqual", dvs[0][:operator])
    assert_equal(true, dvs[0][:show_error_message])
    assert_equal("Must be >= 10", dvs[0][:error])
    assert_equal("Validation Error", dvs[0][:error_title])
    assert_equal("10", dvs[0][:formula1])

    assert_equal("B2:B50", dvs[1][:sqref])
    assert_equal("list", dvs[1][:type])
    assert_equal(true, dvs[1][:show_input_message])
    assert_equal("Pick a color", dvs[1][:prompt])
    assert_equal("Color", dvs[1][:prompt_title])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse conditional formatting generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_conditional_format_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cfs = reader.conditional_formats
    assert_equal(3, cfs.size)

    assert_equal("A1:A10", cfs[0][:sqref])
    assert_equal("cellIs", cfs[0][:type])
    assert_equal("lessThan", cfs[0][:operator])
    assert_equal(["50"], cfs[0][:formulas])

    assert_equal("colorScale", cfs[1][:type])
    cs = cfs[1][:color_scale]
    assert_equal(2, cs[:cfvo].size)
    assert_equal("min", cs[:cfvo][0][:type])
    assert_equal([{ rgb: "FF00FF00" }, { rgb: "FFFF0000" }], cs[:colors])

    assert_equal("dataBar", cfs[2][:type])
    db = cfs[2][:data_bar]
    assert_equal(2, db[:cfvo].size)
    assert_equal({ rgb: "FF63C384" }, db[:color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse expanded styles generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_expanded_styles_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    assert_equal(true, cs["A1"][:font][:bold])
    assert_equal(16.0, cs["A1"][:font][:sz])
    assert_equal("FF0000FF", cs["A1"][:font][:color])
    assert_equal("solid", cs["A1"][:fill][:pattern])
    assert_equal("FFFF0000", cs["A1"][:fill][:fg_color])
    assert_equal("medium", cs["A1"][:border][:left][:style])

    dxfs = reader.dxfs
    assert_equal(1, dxfs.size)
    assert_equal(true, dxfs[0][:font][:bold])
    assert_equal("FF00FF00", dxfs[0][:font][:color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse tables generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_table_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    tbls = reader.tables
    assert_equal(1, tbls.size)
    assert_equal("A1:B2", tbls[0][:ref])
    assert_equal("SdkTable", tbls[0][:name])
    assert_equal([{ name: "Name" }, { name: "Score" }], tbls[0][:columns])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  # --- Phase 2: Steps 131-140 ---

  test "reader can parse images from drawing generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_image_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    imgs = reader.images
    assert_equal(1, imgs.size)
    assert_equal("TestImage", imgs[0][:name])
    assert_not_nil(imgs[0][:embed_rid])
    assert_not_nil(imgs[0][:target])
    assert_equal(0, imgs[0][:from_col])
    assert_equal(0, imgs[0][:from_row])
    assert_equal(5, imgs[0][:to_col])
    assert_equal(10, imgs[0][:to_row])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse image description from drawing generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_image_descr_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    imgs = reader.images
    assert_equal(1, imgs.size)
    assert_equal("DescribedImage", imgs[0][:name])
    assert_equal("Image alt text from SDK", imgs[0][:description])
    assert_not_nil(imgs[0][:target])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse charts from drawing generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("SalesChart", charts[0][:name])
    assert_equal("barChart", charts[0][:chart_type])
    assert_equal("Sales Data", charts[0][:title])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse comments generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_comment_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    comments = reader.comments
    assert_equal(2, comments.size)
    assert_equal("A1", comments[0][:ref])
    assert_equal("TestAuthor", comments[0][:author])
    assert_equal("First comment", comments[0][:text])
    assert_equal("B2", comments[1][:ref])
    assert_equal("SecondAuthor", comments[1][:author])
    assert_equal("Second comment", comments[1][:text])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse rich text comments from SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_comment_rich_text_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    comments = reader.comments
    assert_equal(1, comments.size)
    c = comments[0]
    assert_equal("A1", c[:ref])
    assert_equal("TestAuthor", c[:author])
    assert_instance_of(Xlsxrb::RichText, c[:text])
    assert_equal("Important note text", c[:text].to_s)
    runs = c[:text].runs
    assert_equal(2, runs.size)
    assert_equal("Important", runs[0][:text])
    assert_equal(true, runs[0][:font][:bold])
    assert_equal(11.0, runs[0][:font][:sz])
    assert_equal("Calibri", runs[0][:font][:name])
    assert_equal(" note text", runs[1][:text])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse pivot tables generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_pivot_table_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    pivots = reader.pivot_tables(sheet: 1)
    assert_equal(1, pivots.size)
    assert_equal("TestPivot", pivots[0][:name])
    assert_equal([0], pivots[0][:row_fields])
    assert_equal(1, pivots[0][:data_fields].size)
    assert_equal("Sum of Amount", pivots[0][:data_fields][0][:name])
    assert_equal("sum", pivots[0][:data_fields][0][:subtotal])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "retention: image survives copy_entries_from round-trip" do
    source_tempfile = Tempfile.new(["xlsxrb-retention-src", ".xlsx"])
    source_path = source_tempfile.path
    source_tempfile.close

    output_tempfile = Tempfile.new(["xlsxrb-retention-out", ".xlsx"])
    output_path = output_tempfile.path
    output_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_image_generated_by_sdk", source_path)

    writer = Xlsxrb::Writer.new
    writer.copy_entries_from(source_path)
    writer.write(output_path)

    assert_openxml_sdk_scenario_passes("retention_image_test", output_path)
  ensure
    File.delete(source_path) if source_path && File.exist?(source_path)
    File.delete(output_path) if output_path && File.exist?(output_path)
  end

  test "retention: chart survives copy_entries_from round-trip" do
    source_tempfile = Tempfile.new(["xlsxrb-retention-src", ".xlsx"])
    source_path = source_tempfile.path
    source_tempfile.close

    output_tempfile = Tempfile.new(["xlsxrb-retention-out", ".xlsx"])
    output_path = output_tempfile.path
    output_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_generated_by_sdk", source_path)

    writer = Xlsxrb::Writer.new
    writer.copy_entries_from(source_path)
    writer.write(output_path)

    assert_openxml_sdk_scenario_passes("retention_chart_test", output_path)
  ensure
    File.delete(source_path) if source_path && File.exist?(source_path)
    File.delete(output_path) if output_path && File.exist?(output_path)
  end

  test "retention: comment survives copy_entries_from round-trip" do
    source_tempfile = Tempfile.new(["xlsxrb-retention-src", ".xlsx"])
    source_path = source_tempfile.path
    source_tempfile.close

    output_tempfile = Tempfile.new(["xlsxrb-retention-out", ".xlsx"])
    output_path = output_tempfile.path
    output_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_comment_generated_by_sdk", source_path)

    writer = Xlsxrb::Writer.new
    writer.copy_entries_from(source_path)
    writer.write(output_path)

    assert_openxml_sdk_scenario_passes("retention_comment_test", output_path)
  ensure
    File.delete(source_path) if source_path && File.exist?(source_path)
    File.delete(output_path) if output_path && File.exist?(output_path)
  end

  test "retention: pivot table survives copy_entries_from round-trip" do
    source_tempfile = Tempfile.new(["xlsxrb-retention-src", ".xlsx"])
    source_path = source_tempfile.path
    source_tempfile.close

    output_tempfile = Tempfile.new(["xlsxrb-retention-out", ".xlsx"])
    output_path = output_tempfile.path
    output_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_pivot_table_generated_by_sdk", source_path)

    writer = Xlsxrb::Writer.new
    writer.add_sheet("PivotSheet")
    writer.copy_entries_from(source_path)
    writer.write(output_path)

    assert_openxml_sdk_scenario_passes("retention_pivot_table_test", output_path)
  ensure
    File.delete(source_path) if source_path && File.exist?(source_path)
    File.delete(output_path) if output_path && File.exist?(output_path)
  end

  test "reader can parse sheet protection generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_protection_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    prot = reader.sheet_protection
    assert_not_nil(prot)
    assert_equal(true, prot[:sheet])
    assert_equal("CF1A", prot[:password])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse workbook protection generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_workbook_protection_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    prot = reader.workbook_protection
    assert_not_nil(prot)
    assert_equal(true, prot[:lock_structure])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse rich text from shared strings generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_rich_text_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    result = cells["A1"]
    assert_instance_of(Xlsxrb::RichText, result)
    assert_equal(2, result.runs.size)
    assert_equal("Hello", result.runs[0][:text])
    assert_equal(true, result.runs[0][:font][:bold])
    assert_equal(" World", result.runs[1][:text])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse shared and array formulas generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_formulas_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    b1 = cells["B1"]
    assert_instance_of(Xlsxrb::Formula, b1)
    assert_equal(:shared, b1.type)
    assert_equal("B1:B2", b1.ref)
    assert_equal(0, b1.shared_index)
    assert_equal("A1*2", b1.expression)

    c3 = cells["C3"]
    assert_instance_of(Xlsxrb::Formula, c3)
    assert_equal(:array, c3.type)
    assert_equal("SUM(A1:A2*B1:B2)", c3.expression)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated CF dataBar and iconSet deep attributes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cf_deep_attrs_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cfs = reader.conditional_formats
    assert_equal(2, cfs.size)

    db = cfs[0][:data_bar]
    assert_not_nil(db, "expected dataBar rule")
    assert_equal(5, db[:min_length])
    assert_equal(90, db[:max_length])
    assert_equal(false, db[:show_value])

    is = cfs[1][:icon_set]
    assert_not_nil(is, "expected iconSet rule")
    assert_equal(true, is[:reverse])
    assert_equal(false, is[:show_value])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated DV deep attributes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_dv_deep_attrs_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    dvs = reader.data_validations
    assert_equal(1, dvs.size)
    dv = dvs[0]
    assert_equal(true, dv[:allow_blank])
    assert_equal("warning", dv[:error_style])
    assert_equal("Bad Value", dv[:error_title])
    assert_equal("Please enter 1-100", dv[:error])
    assert_equal("Input Needed", dv[:prompt_title])
    assert_equal("Enter a number", dv[:prompt])
    assert_equal(true, dv[:show_error_message])
    assert_equal(true, dv[:show_input_message])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated cellStyleXfs and cellStyles" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_styles_deep_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)

    csxfs = reader.cell_style_xfs
    assert_equal(2, csxfs.size)
    assert_equal(1, csxfs[1][:font_id])

    ncs = reader.named_cell_styles
    assert_equal(2, ncs.size)
    assert_equal("Normal", ncs[0][:name])
    assert_equal(0, ncs[0][:builtin_id])
    assert_equal("Heading1", ncs[1][:name])
    assert_equal(1, ncs[1][:xf_id])
    assert_equal(1, ncs[1][:builtin_id])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart with multiple series legend and axis titles" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_deep_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("barChart", charts[0][:chart_type])
    assert_equal("Multi Series", charts[0][:title])
    assert_equal(2, charts[0][:series].size)
    assert_equal("b", charts[0][:legend][:position])
    assert_equal(true, charts[0][:data_labels][:show_val])
    assert_equal("Category", charts[0][:cat_axis_title])
    assert_equal("Amount", charts[0][:val_axis_title])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart with legend entries" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_legend_entries_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_not_nil(charts[0][:legend][:entries])
    assert_equal(1, charts[0][:legend][:entries].size)
    assert_equal(0, charts[0][:legend][:entries][0][:idx])
    assert_equal(true, charts[0][:legend][:entries][0][:delete])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart with series line formatting" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_series_line_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    ser = charts[0][:series][0]
    assert_equal("FF5500", ser[:line_color])
    assert_equal(3.0, ser[:line_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart with series marker" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_series_marker_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    ser = charts[0][:series][0]
    assert_equal("triangle", ser[:marker_symbol])
    assert_equal(10, ser[:marker_size])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated image with srcRect cropping" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_src_rect_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    imgs = reader.images
    assert_equal(1, imgs.size)
    sr = imgs[0][:src_rect]
    assert_not_nil(sr)
    assert_equal(15_000, sr[:top])
    assert_equal(25_000, sr[:bottom])
    assert_equal(10_000, sr[:left])
    assert_equal(20_000, sr[:right])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated image with alphaModFix transparency" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_alpha_mod_fix_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    imgs = reader.images
    assert_equal(1, imgs.size)
    assert_equal(75_000, imgs[0][:alpha_mod_fix])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with adjust values" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_adjust_values_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal("roundRect", shapes[0][:preset])
    avs = shapes[0][:adjust_values]
    assert_equal(2, avs.size)
    assert_equal("adj", avs[0][:name])
    assert_equal("val 25000", avs[0][:fmla])
    assert_equal("adj2", avs[1][:name])
    assert_equal("val 50000", avs[1][:fmla])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with text font properties" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_text_font_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    tf = shapes[0][:text_font]
    assert_not_nil(tf)
    assert_equal(true, tf[:bold])
    assert_equal(true, tf[:italic])
    assert_equal(1600, tf[:size])
    assert_equal("00CC00", tf[:color])
    assert_equal("Times New Roman", tf[:name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shapes with autofit modes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_autofit_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(3, shapes.size)
    assert_equal("none", shapes[0][:autofit])
    assert_equal("shape", shapes[1][:autofit])
    assert_equal("normal", shapes[2][:autofit])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with outer shadow" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_outer_shadow_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    os = shapes[0][:outer_shadow]
    assert_not_nil(os)
    assert_equal(63_500, os[:blur_rad])
    assert_equal(50_800, os[:dist])
    assert_equal(5_400_000, os[:dir])
    assert_equal("ctr", os[:algn])
    assert_equal("0000FF", os[:color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with gradient fill" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shape_gradient_fill_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    gf = shapes[0][:gradient_fill]
    assert_not_nil(gf)
    assert_equal(3, gf[:stops].size)
    assert_equal(0, gf[:stops][0][:pos])
    assert_equal("00FF00", gf[:stops][0][:color])
    assert_equal(50_000, gf[:stops][1][:pos])
    assert_equal("FFFF00", gf[:stops][1][:color])
    assert_equal(100_000, gf[:stops][2][:pos])
    assert_equal("FF00FF", gf[:stops][2][:color])
    assert_equal(2_700_000, gf[:angle])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with line dash style" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_line_dash_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal("dashDot", shapes[0][:line_dash])
    assert_equal("FF0000", shapes[0][:line_color])
    assert_equal(25_400, shapes[0][:line_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape with line end arrows" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_line_end_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal("diamond", shapes[0][:head_end][:type])
    assert_equal("sm", shapes[0][:head_end][:w])
    assert_equal("sm", shapes[0][:head_end][:len])
    assert_equal("arrow", shapes[0][:tail_end][:type])
    assert_equal("lg", shapes[0][:tail_end][:w])
    assert_equal("med", shapes[0][:tail_end][:len])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shapes with preset geometry and text" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shape_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(2, shapes.size)
    assert_equal("ellipse", shapes[0][:preset])
    assert_equal("ShapeText", shapes[0][:text])
    assert_equal("Oval 1", shapes[0][:name])
    assert_equal(1, shapes[0][:from_col])
    assert_equal(2, shapes[0][:from_row])
    assert_equal("roundRect", shapes[1][:preset])
    assert_equal("RoundRect 1", shapes[1][:name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated pivot table with col_fields and items" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_pivot_deep_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    pts = reader.pivot_tables
    assert_equal(1, pts.size)
    assert_equal("PivotDeep", pts[0][:name])
    assert_equal([0], pts[0][:row_fields])
    assert_equal([1], pts[0][:col_fields])
    assert_equal("axisRow", pts[0][:fields][0][:axis])
    assert_equal("axisCol", pts[0][:fields][1][:axis])
    # Items parsed
    assert_equal(3, pts[0][:fields][0][:items].size)
    assert_equal("default", pts[0][:fields][0][:items].last[:t])
    # Cache definition parsed
    cache = pts[0][:cache]
    assert_not_nil(cache)
    assert_equal("worksheet", cache[:source_type])
    assert_equal("Sheet1", cache[:source_sheet])
    assert_equal("A1:C4", cache[:source_ref])
    assert_equal(3, cache[:fields].size)
    assert_equal("Category", cache[:fields][0][:name])
    assert_equal("Region", cache[:fields][1][:name])
    assert_equal("Amount", cache[:fields][2][:name])
    assert_equal(%w[A B], cache[:fields][0][:shared_items])
    assert_equal(%w[East West], cache[:fields][1][:shared_items])
    # Cache records parsed
    assert_not_nil(cache[:records])
    assert_equal(2, cache[:records].size)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated external link" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_external_link_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    els = reader.external_links
    assert_equal(1, els.size)
    assert_equal(%w[RemoteSheet1 RemoteSheet2], els[0][:sheet_names])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated table with totals row and deep columns" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_table_deep_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    tbls = reader.tables
    assert_equal(1, tbls.size)
    assert_equal(1, tbls[0][:totals_row_count])
    assert_equal("sum", tbls[0][:columns][1][:totals_row_function])
    assert_equal("[Price]*0.1", tbls[0][:columns][2][:calculated_column_formula])
    assert_equal("TableStyleLight1", tbls[0][:style][:name])
    assert_equal(true, tbls[0][:style][:show_column_stripes])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reads cell alignment from SDK-generated XLSX" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_alignment_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    alignment = cs["A1"][:alignment]
    assert_not_nil(alignment, "alignment should be present")
    assert_equal("center", alignment[:horizontal])
    assert_equal("top", alignment[:vertical])
    assert_equal(true, alignment[:wrap_text])
    assert_equal(45, alignment[:text_rotation])
    assert_equal(2, alignment[:indent])
    assert_equal(true, alignment[:shrink_to_fit])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reads extended font attributes from SDK-generated XLSX" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_font_extended_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    font = cs["A1"][:font]
    assert_not_nil(font, "font should be present")
    assert_equal(true, font[:bold])
    assert_equal(true, font[:italic])
    assert_equal(true, font[:strike])
    assert_equal("double", font[:underline])
    assert_equal("superscript", font[:vert_align])
    assert_equal("minor", font[:scheme])
    assert_equal(2, font[:family])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reads gradient fill from SDK-generated XLSX" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_gradient_fill_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    fill = cs["A1"][:fill]
    assert_not_nil(fill, "fill should be present")
    gradient = fill[:gradient]
    assert_not_nil(gradient, "gradient should be present")
    assert_equal("linear", gradient[:type])
    assert_equal(90.0, gradient[:degree])
    assert_equal(2, gradient[:stops].size)
    assert_equal("FFFF0000", gradient[:stops][0][:color])
    assert_equal("FF0000FF", gradient[:stops][1][:color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reads diagonal border from SDK-generated XLSX" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_diagonal_border_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    border = cs["A1"][:border]
    assert_not_nil(border, "border should be present")
    assert_equal(true, border[:diagonal_up])
    assert_equal(true, border[:diagonal_down])
    assert_equal("thin", border[:diagonal][:style])
    assert_equal("FFFF0000", border[:diagonal][:color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reads cell protection from SDK-generated XLSX" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cell_protection_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    assert(cs.key?("A1"), "A1 should have a style")
    prot = cs["A1"][:protection]
    assert_not_nil(prot, "protection should be present")
    assert_equal(false, prot[:locked])
    assert_equal(true, prot[:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated expanded CF rule types" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cf_expanded_types_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cfs = reader.conditional_formats
    assert_equal(6, cfs.size)

    # aboveAverage (below average, equal)
    assert_equal("aboveAverage", cfs[0][:type])
    assert_equal(false, cfs[0][:above_average])
    assert_equal(true, cfs[0][:equal_average])

    # top10 (bottom 5 percent)
    assert_equal("top10", cfs[1][:type])
    assert_equal(5, cfs[1][:rank])
    assert_equal(true, cfs[1][:percent])
    assert_equal(true, cfs[1][:bottom])

    # duplicateValues
    assert_equal("duplicateValues", cfs[2][:type])

    # containsText
    assert_equal("containsText", cfs[3][:type])
    assert_equal("hello", cfs[3][:text])

    # beginsWith
    assert_equal("beginsWith", cfs[4][:type])
    assert_equal("foo", cfs[4][:text])

    # endsWith
    assert_equal("endsWith", cfs[5][:type])
    assert_equal("bar", cfs[5][:text])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated rich text with extended font attributes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_rich_text_extended_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    val = reader.cells["A1"]
    assert_instance_of(Xlsxrb::RichText, val)
    runs = val.runs

    assert_equal(5, runs.size)

    # strike
    assert_equal(true, runs[0][:font][:strike])

    # double underline
    assert_equal("double", runs[1][:font][:underline])

    # superscript
    assert_equal("superscript", runs[2][:font][:vert_align])

    # theme color + family + scheme
    assert_equal(1, runs[3][:font][:theme])
    assert_in_delta(0.5, runs[3][:font][:tint], 0.001)
    assert_equal(2, runs[3][:font][:family])
    assert_equal("minor", runs[3][:font][:scheme])

    # indexed color
    assert_equal(10, runs[4][:font][:indexed])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated CF theme/indexed colors" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cf_theme_color_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cfs = reader.conditional_formats
    assert_equal(2, cfs.size)

    cs_colors = cfs[0][:color_scale][:colors]
    assert_equal(2, cs_colors.size)
    assert_equal(4, cs_colors[0][:theme])
    assert_in_delta(-0.25, cs_colors[0][:tint], 0.001)
    assert_equal(9, cs_colors[1][:theme])

    db_color = cfs[1][:data_bar][:color]
    assert_equal(10, db_color[:indexed])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated gradient fill with theme/indexed stop colors" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_gradient_stop_theme_color_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cs = reader.cell_styles
    gradient = cs["A1"][:fill][:gradient]
    assert_not_nil(gradient, "gradient should be present")
    stops = gradient[:stops]
    assert_equal(2, stops.size)
    assert_equal(4, stops[0][:theme])
    assert_in_delta(-0.5, stops[0][:tint], 0.001)
    assert_equal(12, stops[1][:indexed])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated complete CF rule types" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cf_complete_types_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    cfs = reader.conditional_formats
    assert_equal(6, cfs.size)

    assert_equal("expression", cfs[0][:type])
    assert_equal("uniqueValues", cfs[1][:type])
    assert_equal("notContainsText", cfs[2][:type])
    assert_equal("bad", cfs[2][:text])
    assert_equal("containsBlanks", cfs[3][:type])
    assert_equal("notContainsBlanks", cfs[4][:type])
    assert_equal("timePeriod", cfs[5][:type])
    assert_equal("lastWeek", cfs[5][:time_period])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated DXF with alignment, protection, numFmt" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_dxf_deep_attrs_generated_by_sdk", xlsx_path)
    reader = Xlsxrb::Reader.new(xlsx_path)
    dxfs = reader.dxfs
    assert_equal(1, dxfs.size)
    dxf = dxfs[0]

    assert_equal(true, dxf[:font][:bold])
    assert_equal(164, dxf[:num_fmt][:num_fmt_id])
    assert_equal("#,##0.00", dxf[:num_fmt][:format_code])
    assert_equal("center", dxf[:alignment][:horizontal])
    assert_equal(true, dxf[:alignment][:wrap_text])
    assert_equal(false, dxf[:protection][:locked])
    assert_equal(true, dxf[:protection][:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses extended core properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_core_properties_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.core_properties

    assert_equal("SDK Title", props[:title])
    assert_equal("SDK Subject", props[:subject])
    assert_equal("SDK Creator", props[:creator])
    assert_equal("sdk, test", props[:keywords])
    assert_equal("SDK Description", props[:description])
    assert_equal("SDK Editor", props[:last_modified_by])
    assert_equal("5", props[:revision])
    assert_equal("Testing", props[:category])
    assert_equal("Final", props[:content_status])
    assert_equal("ja-JP", props[:language])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses split pane generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_split_pane_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    pane = reader.freeze_pane

    assert_equal(:split, pane[:state])
    assert_equal(3000, pane[:x_split])
    assert_equal(2000, pane[:y_split])
    assert_equal("D5", pane[:top_left_cell])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses colorFilter and iconFilter generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_color_icon_filter_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    filters = reader.filter_columns

    cf = filters[0]
    assert_equal(:color_filter, cf[:type])
    assert_equal(0, cf[:dxf_id])

    icf = filters[1]
    assert_equal(:icon_filter, icf[:type])
    assert_equal("3Arrows", icf[:icon_set])
    assert_equal(1, icf[:icon_id])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses datetime as Time from SDK-generated fractional serial" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_datetime_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells

    val = cells["A1"]
    assert_instance_of(Time, val)
    assert_equal(2024, val.year)
    assert_equal(6, val.month)
    assert_equal(15, val.day)
    assert_equal(10, val.hour)
    assert_equal(15, val.min)
    assert_equal(30, val.sec)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses print area and print titles from SDK-generated file" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_print_area_titles_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)

    pa = reader.print_area
    assert_equal("$A$1:$E$50", pa)

    pt = reader.print_titles
    assert_not_nil(pt)
    assert(pt.include?("$A:$C"), "Expected print titles to contain '$A:$C' but got '#{pt}'")
    assert(pt.include?("$1:$5"), "Expected print titles to contain '$1:$5' but got '#{pt}'")
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses first page header/footer and differentFirst/differentOddEven from SDK-generated file" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_header_footer_first_page_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    hf = reader.header_footer

    assert_equal(true, hf[:different_first])
    assert_equal(true, hf[:different_odd_even])
    assert_equal("&CFirst Page Header", hf[:first_header])
    assert_equal("&CFirst Page Footer", hf[:first_footer])
    assert_equal("&LOdd Header", hf[:odd_header])
    assert_equal("&LEven Header", hf[:even_header])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses extended page setup attributes from SDK-generated file" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_page_setup_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ps = reader.page_setup
    assert_equal("overThenDown", ps[:page_order])
    assert_equal(true, ps[:black_and_white])
    assert_equal(true, ps[:draft])
    assert_equal("atEnd", ps[:cell_comments])
    assert_equal(5, ps[:first_page_number])
    assert_equal(true, ps[:use_first_page_number])
    assert_equal(300, ps[:horizontal_dpi])
    assert_equal(300, ps[:vertical_dpi])
    assert_equal("landscape", ps[:orientation])
    assert_equal(9, ps[:paper_size])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses data validation showDropDown and imeMode from SDK-generated file" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_data_validation_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    dvs = reader.data_validations

    assert_equal(1, dvs.size)
    dv = dvs.first
    assert_equal(true, dv[:show_drop_down])
    assert_equal("hiragana", dv[:ime_mode])
    assert_equal("list", dv[:type])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses alignment readingOrder and justifyLastLine from SDK-generated file" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_alignment_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    styles = reader.cell_styles
    xf = styles.values.find { |s| s[:alignment]&.key?(:reading_order) }
    assert_not_nil(xf, "Expected a cell style with readingOrder")
    assert_equal(2, xf[:alignment][:reading_order])
    assert_equal(true, xf[:alignment][:justify_last_line])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse showFormulas on sheet view generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_show_formulas_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    sv = reader.sheet_view
    assert_equal(true, sv[:show_formulas])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse codeName on sheet properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_code_name_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.sheet_properties
    assert_equal("MySheet", props[:code_name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse workbook view visibility generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_workbook_view_visibility_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    wv = reader.workbook_views
    assert_equal("hidden", wv[:visibility])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse phonetic properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_phonetic_pr_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    pp = reader.phonetic_properties
    assert_not_nil(pp)
    assert_equal(1, pp[:font_id])
    assert_equal("Hiragana", pp[:type])
    assert_equal("center", pp[:alignment])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse custom document properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_custom_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.custom_properties
    assert_not_nil(props)

    project = props.find { |p| p[:name] == "Project" }
    assert_not_nil(project)
    assert_equal("Alpha", project[:value])

    version = props.find { |p| p[:name] == "Version" }
    assert_not_nil(version)
    assert_equal(42, version[:value])

    active = props.find { |p| p[:name] == "Active" }
    assert_not_nil(active)
    assert_equal(true, active[:value])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse font shadow outline condense extend generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_font_effects_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    styles = reader.cell_styles
    styled_font = styles.values.map { |s| s[:font] }.compact.find { |f| f[:shadow] }
    assert_not_nil(styled_font)
    assert_equal(true, styled_font[:shadow])
    assert_equal(true, styled_font[:outline])
    assert_equal(true, styled_font[:condense])
    assert_equal(true, styled_font[:extend])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheetView showZeros view showOutlineSymbols showRuler from SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_view_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    sv = reader.sheet_view
    assert_equal(false, sv[:show_zeros])
    assert_equal("pageBreakPreview", sv[:view])
    assert_equal(false, sv[:show_outline_symbols])
    assert_equal(false, sv[:show_ruler])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated fileVersion element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_file_version_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fv = reader.file_version
    assert_equal("xl", fv[:app_name])
    assert_equal("7", fv[:last_edited])
    assert_equal("7", fv[:lowest_edited])
    assert_equal("27425", fv[:rup_build])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated fileSharing element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_file_sharing_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fs = reader.file_sharing
    assert_equal(true, fs[:read_only_recommended])
    assert_equal("TestUser", fs[:user_name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated protectedRanges element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_protected_ranges_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ranges = reader.protected_ranges
    assert_equal(2, ranges.size)
    assert_equal("EditArea", ranges[0][:name])
    assert_equal("A1:B10", ranges[0][:sqref])
    assert_equal("SHA-512", ranges[1][:algorithm_name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated indexed colors" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_indexed_colors_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ic = reader.indexed_colors
    assert_equal("FF000000", ic[0])
    assert_equal("FFFFFFFF", ic[1])
    assert_equal("FFFF0000", ic[2])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated tableStyles element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_table_styles_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ts = reader.table_styles
    assert_equal("TableStyleMedium2", ts[:default_table_style])
    assert_equal("PivotStyleLight16", ts[:default_pivot_style])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated cellWatches element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_cell_watches_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    watches = reader.cell_watches
    assert_equal(%w[A1 B2], watches)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated dataConsolidate element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_data_consolidate_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    dc = reader.data_consolidate
    assert_equal("average", dc[:function])
    assert_equal(true, dc[:start_labels])
    assert_equal(true, dc[:link])
    assert_equal(2, dc[:data_refs].size)
    assert_equal("A1:B10", dc[:data_refs][0][:ref])
    assert_equal("Sheet1", dc[:data_refs][0][:sheet])
    assert_equal("Range2", dc[:data_refs][1][:name])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated scenarios element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_scenarios_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    sc = reader.scenarios
    assert_equal(0, sc[:current])
    assert_equal(0, sc[:show])
    assert_equal(1, sc[:scenarios].size)
    assert_equal("Best Case", sc[:scenarios][0][:name])
    assert_equal("Admin", sc[:scenarios][0][:user])
    assert_equal(2, sc[:scenarios][0][:input_cells].size)
    assert_equal("A1", sc[:scenarios][0][:input_cells][0][:r])
    assert_equal("200", sc[:scenarios][0][:input_cells][0][:val])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated ignoredErrors element" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_ignored_errors_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    errors = reader.ignored_errors
    assert_equal(1, errors.size)
    assert_equal("A1", errors[0][:sqref])
    assert_equal(true, errors[0][:number_stored_as_text])
    assert_equal(true, errors[0][:formula_range])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated autoFilter extended attributes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_auto_filter_extended_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fcs = reader.filter_columns
    assert_equal(true, fcs[0][:hidden_button])
    assert_equal(1, fcs[0][:date_group_items].size)
    assert_equal("year", fcs[0][:date_group_items][0][:date_time_grouping])
    assert_equal(2024, fcs[0][:date_group_items][0][:year])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated conformance attribute" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_conformance_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal("transitional", reader.conformance)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated totalsRowFormula in table column" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_totals_row_formula_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    tbls = reader.tables
    assert_equal(1, tbls.size)
    assert_equal("SUBTOTAL(109,[Price])", tbls[0][:columns][1][:totals_row_formula])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated view3D element in chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_view3d_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(30, charts[0][:view_3d][:rot_x])
    assert_equal(20, charts[0][:view_3d][:rot_y])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated numFmt on chart axes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_numfmt_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("General", charts[0][:cat_axis_num_fmt][:format_code])
    assert_equal(true, charts[0][:cat_axis_num_fmt][:source_linked])
    assert_equal("0.00", charts[0][:val_axis_num_fmt][:format_code])
    assert_equal(false, charts[0][:val_axis_num_fmt][:source_linked])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated majorTickMark and minorTickMark on chart axes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_tickmark_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("cross", charts[0][:cat_axis_major_tick_mark])
    assert_equal("in", charts[0][:cat_axis_minor_tick_mark])
    assert_equal("out", charts[0][:val_axis_major_tick_mark])
    assert_equal("none", charts[0][:val_axis_minor_tick_mark])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated crosses elements on chart axes" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_crosses_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("autoZero", charts[0][:cat_axis_crosses])
    assert_equal("max", charts[0][:val_axis_crosses])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated crossBetween, majorUnit, minorUnit on value axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_val_axis_units_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("between", charts[0][:val_axis_cross_between])
    assert_equal(10.0, charts[0][:val_axis_major_unit])
    assert_equal(2.0, charts[0][:val_axis_minor_unit])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated scaling max and min on chart value axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_scaling_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(100.0, charts[0][:val_axis_scaling_max])
    assert_equal(0.0, charts[0][:val_axis_scaling_min])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated logBase element in chart axis scaling" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_logbase_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(10.0, charts[0][:val_axis_log_base])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated firstSliceAng and holeSize in doughnut chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_pie_angles_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(45, charts[0][:first_slice_ang])
    assert_equal(50, charts[0][:hole_size])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated smooth and marker elements in line chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_line_chart_smooth_marker_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(true, charts[0][:smooth])
    assert_equal(true, charts[0][:marker])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated dropLines and hiLowLines in line chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_drop_lines_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(true, charts[0][:drop_lines])
    assert_equal(true, charts[0][:hi_low_lines])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated upDownBars in line chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_up_down_bars_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_not_nil(charts[0][:up_down_bars])
    assert_equal(250, charts[0][:up_down_bars][:gap_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated scatterStyle element in scatter chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_scatter_style_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("lineMarker", charts[0][:scatter_style])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated gapDepth and shape for 3D bar chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_bar3d_gap_shape_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(150, charts[0][:gap_depth])
    assert_equal("cylinder", charts[0][:bar_shape])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated bubbleScale, showNegBubbles, sizeRepresents in bubble chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_bubble_chart_props_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(80, charts[0][:bubble_scale])
    assert_equal(false, charts[0][:show_neg_bubbles])
    assert_equal("area", charts[0][:size_represents])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated crossesAt on value axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_crosses_at_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_in_delta(5.0, charts[0][:val_axis_crosses_at])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated wireframe element in surface chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_surface_wireframe_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(true, charts[0][:wireframe])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated tickLblSkip and tickMarkSkip on category axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_tick_skip_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(2, charts[0][:cat_axis_tick_lbl_skip])
    assert_equal(3, charts[0][:cat_axis_tick_mark_skip])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated lblOffset and noMultiLvlLbl on category axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_lbl_offset_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal(50, charts[0][:cat_axis_lbl_offset])
    assert_equal(true, charts[0][:cat_axis_no_multi_lvl_lbl])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated dispUnits/builtInUnit on value axis" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_axis_disp_units_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("thousands", charts[0][:val_axis_disp_units])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated fileRecoveryPr in workbook" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_file_recovery_pr_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    frp = reader.file_recovery_properties
    assert_equal(false, frp[:auto_recover])
    assert_equal(true, frp[:crash_save])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape solidFill color" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shape_fill_color_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal("FF0000", shapes[0][:fill_color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape line color and width" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shape_line_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal("0000FF", shapes[0][:line_color])
    assert_equal(12_700, shapes[0][:line_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated image line color and width" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_image_line_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    imgs = reader.images
    assert_equal(1, imgs.size)
    assert_equal("FF0000", imgs[0][:line_color])
    assert_equal(25_400, imgs[0][:line_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated shape noFill and noLine" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shape_no_fill_no_line_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    shapes = reader.shapes
    assert_equal(1, shapes.size)
    assert_equal(true, shapes[0][:no_fill])
    assert_equal(true, shapes[0][:no_line])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart data table (dTable)" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_data_table_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    dt = charts[0][:data_table]
    assert_equal(true, dt[:show_horz_border])
    assert_equal(false, dt[:show_vert_border])
    assert_equal(true, dt[:show_outline])
    assert_equal(true, dt[:show_keys])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart series fill color" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_series_fill_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("00FF00", charts[0][:series][0][:fill_color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated chart plot area fill color" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-sdk", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_chart_plot_area_fill_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    assert_equal("CCCCCC", charts[0][:plot_area_fill])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated series data points in pie chart" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_data_points_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    ser = charts[0][:series].first
    assert_not_nil(ser[:data_points])
    assert_equal(3, ser[:data_points].size)
    assert_equal(0, ser[:data_points][0][:idx])
    assert_equal("FF0000", ser[:data_points][0][:fill_color])
    assert_equal(1, ser[:data_points][1][:idx])
    assert_equal("00FF00", ser[:data_points][1][:fill_color])
    assert_equal(2, ser[:data_points][2][:idx])
    assert_equal("0000FF", ser[:data_points][2][:fill_color])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader parses SDK-generated trendline in line chart series" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_trendline_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    charts = reader.charts
    assert_equal(1, charts.size)
    ser = charts[0][:series].first
    tl = ser[:trendline]
    assert_not_nil(tl)
    assert_equal("linear", tl[:type])
    assert_equal("SDK Trend", tl[:name])
    assert_in_delta(3.0, tl[:forward])
    assert_in_delta(1.5, tl[:backward])
    assert_in_delta(2.0, tl[:intercept])
    assert_equal(true, tl[:disp_r_sqr])
    assert_equal(false, tl[:disp_eq])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  private

  def assert_openxml_sdk_scenario_passes(scenario_name, xlsx_path)
    return if OpenXmlSdkScenarioRunner.copy_reader_fixture(scenario_name, xlsx_path)

    scenario_path = File.join(SCENARIO_DIR, "#{scenario_name}.cs")
    assert(File.exist?(scenario_path), "Scenario file not found: #{scenario_path}")

    result = OpenXmlSdkScenarioRunner.run_single_scenario(scenario_path, xlsx_path)
    failure_reason = extract_failure_reason(result[:stderr])

    assert(
      result[:success],
      "Open XML SDK scenario failed: #{failure_reason}\n" \
      "Scenario: #{scenario_name}\n" \
      "XLSX: #{xlsx_path}\n" \
      "STDERR:\n#{result[:stderr]}"
    )
  end

  def extract_failure_reason(stderr)
    return "unknown reason" if stderr.nil? || stderr.strip.empty?

    lines = stderr.lines.map(&:strip).reject(&:empty?)
    exception_line = lines.find { |line| line.include?("Exception:") }
    return exception_line if exception_line

    scenario_line = lines.find { |line| line.start_with?("SCENARIO_") }
    return scenario_line if scenario_line

    lines.first
  end
end
