# frozen_string_literal: true

require "test_helper"
require "open3"
require "tempfile"

class ReaderInteroperabilityTest < Test::Unit::TestCase
  SCENARIO_DIR = File.expand_path("../fixtures/sdk_scenarios", __dir__)

  test "reader can parse inline string file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_inline_string_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple inline strings in the same row generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_same_row_multiple_inline_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse shared strings file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shared_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse numeric cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_numeric_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => 42, "B1" => 3.14 }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse boolean cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_boolean_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => true, "B1" => false }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse error cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_error_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "#DIV/0!", "B1" => "#VALUE!" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse formula cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_formula_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_instance_of(Xlsxrb::Formula, cells["A3"])
    assert_equal("SUM(A1:A2)", cells["A3"].expression)
    assert_equal("30", cells["A3"].cached_value)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple sheets generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_multi_sheet_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[Sheet1 Data], reader.sheet_names)
    assert_equal({ "A1" => "main" }, reader.cells(sheet: "Sheet1"))
    assert_equal({ "A1" => "data" }, reader.cells(sheet: "Data"))
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse column widths generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_column_width_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cols = reader.columns
    assert_in_delta(20.0, cols["A"], 0.01)
    assert_in_delta(15.5, cols["C"], 0.01)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse row attributes generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_row_attributes_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    row_attrs = reader.row_attributes
    assert_in_delta(25.0, row_attrs[1][:height], 0.01)
    assert_equal(true, row_attrs[3][:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse merge cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_merge_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[A1:B2 C3:D4], reader.merged_cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  private

  def assert_openxml_sdk_scenario_passes(scenario_name, xlsx_path)
    scenario_path = File.join(SCENARIO_DIR, "#{scenario_name}.cs")
    assert(File.exist?(scenario_path), "Scenario file not found: #{scenario_path}")

    command = sdk_runner_command(scenario_path, xlsx_path)
    stdout, stderr, status = Open3.capture3(*command)

    failure_reason = extract_failure_reason(stderr)

    assert(
      status.success?,
      "Open XML SDK scenario failed: #{failure_reason}\n" \
      "Scenario: #{scenario_name}\n" \
      "Command: #{command.join(" ")}\n" \
      "XLSX: #{xlsx_path}\n" \
      "STDOUT:\n#{stdout}\n" \
      "STDERR:\n#{stderr}"
    )
  end

  def extract_failure_reason(stderr)
    return "unknown reason" if stderr.nil? || stderr.strip.empty?

    lines = stderr.lines.map(&:strip).reject(&:empty?)
    exception_line = lines.find { |line| line.include?("Exception:") }
    return exception_line if exception_line

    scenario_line = lines.find { |line| line.start_with?("SCENARIO_") }
    return scenario_line if scenario_line

    lines.first
  end

  def sdk_runner_command(scenario_path, xlsx_path)
    [
      "dotnet", File.expand_path("../../vendor/sdk_runner/bin/Release/net8.0/sdk_runner.dll", __dir__),
      scenario_path, xlsx_path
    ]
  end
end
