# frozen_string_literal: true

require "test_helper"
require "open3"
require "tempfile"

class ReaderInteroperabilityTest < Test::Unit::TestCase
  SCENARIO_DIR = File.expand_path("../fixtures/sdk_scenarios", __dir__)

  test "reader can parse inline string file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_inline_string_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple inline strings in the same row generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_same_row_multiple_inline_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse shared strings file generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_shared_strings_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "hello", "B1" => "world" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse numeric cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_numeric_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => 42, "B1" => 3.14 }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse boolean cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_boolean_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => true, "B1" => false }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse error cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_error_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "#DIV/0!", "B1" => "#VALUE!" }, reader.cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse formula cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_formula_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_instance_of(Xlsxrb::Formula, cells["A3"])
    assert_equal("SUM(A1:A2)", cells["A3"].expression)
    assert_equal("30", cells["A3"].cached_value)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse multiple sheets generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_multi_sheet_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[Sheet1 Data], reader.sheet_names)
    assert_equal({ "A1" => "main" }, reader.cells(sheet: "Sheet1"))
    assert_equal({ "A1" => "data" }, reader.cells(sheet: "Data"))
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse column widths generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_column_width_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cols = reader.columns
    assert_in_delta(20.0, cols["A"], 0.01)
    assert_in_delta(15.5, cols["C"], 0.01)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse row attributes generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_row_attributes_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    row_attrs = reader.row_attributes
    assert_in_delta(25.0, row_attrs[1][:height], 0.01)
    assert_equal(true, row_attrs[3][:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse merge cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_merge_cells_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal(%w[A1:B2 C3:D4], reader.merged_cells)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse hyperlinks generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_hyperlink_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal({ "A1" => "https://example.com" }, reader.hyperlinks)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse numFmt from styles generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_numfmt_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fmts = reader.cell_formats
    assert_equal("#,##0.00", fmts["A1"])
    assert_nil(fmts["B1"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse date cells generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_date_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    cells = reader.cells
    assert_equal(Date.new(2024, 1, 15), cells["A1"])
    assert_equal(42, cells["B1"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse auto filter generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_auto_filter_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    assert_equal("A1:B10", reader.auto_filter)
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse core properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_core_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.core_properties
    assert_equal("SDK Title", props[:title])
    assert_equal("SDK Creator", props[:creator])
    assert_not_nil(props[:created])
    assert_not_nil(props[:modified])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse app properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_app_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.app_properties
    assert_equal("SDK App", props[:application])
    assert_equal("2.0.0", props[:app_version])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse workbook properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_workbook_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    wp = reader.workbook_properties
    assert_equal(false, wp[:date1904])
    assert_equal(166_925, wp[:default_theme_version])

    wv = reader.workbook_views
    assert_equal(1, wv[:active_tab])
    assert_equal(0, wv[:first_sheet])

    cp = reader.calc_properties
    assert_equal(191_029, cp[:calc_id])
    assert_equal(true, cp[:full_calc_on_load])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet states generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_state_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    states = reader.sheet_states
    assert_equal(:visible, states["Sheet1"])
    assert_equal(:hidden, states["Hidden"])
    assert_equal(:very_hidden, states["VeryHidden"])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse defined names generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_defined_names_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    dns = reader.defined_names
    assert_equal(3, dns.size)
    assert_equal("MyRange", dns[0][:name])
    assert_equal("Sheet1!$A$1:$B$10", dns[0][:value])
    assert_equal("LocalName", dns[1][:name])
    assert_equal(1, dns[1][:local_sheet_id])
    assert_equal("HiddenConst", dns[2][:name])
    assert_equal(true, dns[2][:hidden])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_properties_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    props = reader.sheet_properties
    assert_equal("FFFF0000", props[:tab_color])
    assert_equal(false, props[:summary_below])
    assert_equal(false, props[:summary_right])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet format properties generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_format_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    fmt = reader.sheet_format
    assert_equal(20.0, fmt[:default_row_height])
    assert_equal(15.5, fmt[:default_col_width])
    assert_equal(12, fmt[:base_col_width])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse row and column attributes generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_row_col_attrs_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    ra = reader.row_attributes
    assert_equal(1, ra[2][:outline_level])
    assert_equal(true, ra[3][:collapsed])

    ca = reader.column_attributes
    assert_equal(true, ca["B"][:hidden])
    assert_equal(2, ca["C"][:outline_level])
    assert_equal(true, ca["C"][:collapsed])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  test "reader can parse sheet view, pane, and selection generated by Open XML SDK" do
    xlsx_tempfile = Tempfile.new(["xlsxrb-reader-e2e", ".xlsx"])
    xlsx_path = xlsx_tempfile.path
    xlsx_tempfile.close

    assert_openxml_sdk_scenario_passes("reader_sheet_view_generated_by_sdk", xlsx_path)

    reader = Xlsxrb::Reader.new(xlsx_path)
    sv = reader.sheet_view
    assert_equal(false, sv[:show_grid_lines])
    assert_equal(120, sv[:zoom_scale])

    fp = reader.freeze_pane
    assert_equal(2, fp[:row])
    assert_equal(1, fp[:col])
    assert_equal(:frozen, fp[:state])

    sel = reader.selection
    assert_equal("D4", sel[:active_cell])
    assert_equal("D4", sel[:sqref])
  ensure
    File.delete(xlsx_path) if xlsx_path && File.exist?(xlsx_path)
  end

  private

  def assert_openxml_sdk_scenario_passes(scenario_name, xlsx_path)
    scenario_path = File.join(SCENARIO_DIR, "#{scenario_name}.cs")
    assert(File.exist?(scenario_path), "Scenario file not found: #{scenario_path}")

    command = sdk_runner_command(scenario_path, xlsx_path)
    stdout, stderr, status = Open3.capture3(*command)

    failure_reason = extract_failure_reason(stderr)

    assert(
      status.success?,
      "Open XML SDK scenario failed: #{failure_reason}\n" \
      "Scenario: #{scenario_name}\n" \
      "Command: #{command.join(" ")}\n" \
      "XLSX: #{xlsx_path}\n" \
      "STDOUT:\n#{stdout}\n" \
      "STDERR:\n#{stderr}"
    )
  end

  def extract_failure_reason(stderr)
    return "unknown reason" if stderr.nil? || stderr.strip.empty?

    lines = stderr.lines.map(&:strip).reject(&:empty?)
    exception_line = lines.find { |line| line.include?("Exception:") }
    return exception_line if exception_line

    scenario_line = lines.find { |line| line.start_with?("SCENARIO_") }
    return scenario_line if scenario_line

    lines.first
  end

  def sdk_runner_command(scenario_path, xlsx_path)
    [
      "dotnet", File.expand_path("../../vendor/sdk_runner/bin/Release/net8.0/sdk_runner.dll", __dir__),
      scenario_path, xlsx_path
    ]
  end
end
