name: Performance
 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance:
    runs-on: ubuntu-latest
    name: Memory & Performance Tests
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
      - name: Run Performance Tests
        run: bundle exec rake test:perf
